FROM python:3.11-slim

WORKDIR /app

# Copy everything you need into the image
COPY serve.py ./
COPY database ./database
COPY embeddings ./embeddings
COPY static ./static
COPY templates ./templates

RUN python3 -m venv venv \
    && . venv/bin/activate \
    && pip install --upgrade pip \
    && pip install fastapi uvicorn sentence-transformers python-dotenv asyncpg python-multipart

EXPOSE 8000

CMD ["/app/venv/bin/python", "serve.py"]
